import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import Footer from './components/Footer'

const poppin = Poppins({ subsets:['latin'], weight:['100', '200', '300', '400', '500', '600', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppin.className}>
        <Nav />
        <main className='px-4 md:px-8 lg:px-12 xl:px-40 py-2'>
           {children}
        </main>
       
        <Footer />
        </body>
    </html>
  )
}
